# Generated by Django 3.2 on 2021-04-09 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('ID', models.IntegerField(primary_key=True, serialize=False)),
                ('Title', models.CharField(max_length=100)),
                ('Author', models.CharField(max_length=100)),
                ('Publisher', models.CharField(max_length=100)),
                ('Edition', models.CharField(max_length=100)),
                ('ISBN', models.CharField(max_length=100)),
                ('Price', models.IntegerField()),
            ],
        ),
    ]
