# Generated by Django 3.2.4 on 2021-06-23 03:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insem', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='Author',
            new_name='Category',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='Publisher',
            new_name='Name',
        ),
    ]
